site_name: OGC API - EDR Part 3 Service Profile Generator
site_description: Authoritative tooling for creating OGC API - EDR Part 3 Service Profiles
site_author: Shane Mill (NOAA/NWS/MDL)
site_url: https://shanemill1.github.io/OGC-Service-Profile-Creation/
repo_url: https://github.com/ShaneMill1/OGC-Service-Profile-Creation
repo_name: GitHub

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShaneMill1/OGC-Service-Profile-Creation
